/**
 * Mock Data untuk Development
 * Data dummy yang structure-nya sesuai dengan expected API response
 */

import { DashboardApiResponse } from '@/@types/dashboard';

export const MOCK_DASHBOARD_DATA: DashboardApiResponse = {
  kpis: [
    {
      id: 'bca-usd',
      title: 'BCA (USD)',
      value: 999_999_999,
      currency: 'USD',
      trend: 'up',
      trendPercentage: 12,
      trendLabel: 'Naik dibanding bulan lalu',
    },
    {
      id: 'bca-idr',
      title: 'BCA (IDR)',
      value: 999_999_999,
      currency: 'IDR',
      trend: 'up',
      trendPercentage: 8,
      trendLabel: 'Naik dibanding bulan lalu',
    },
    {
      id: 'cash',
      title: 'Cash (IDR)',
      value: 999_999_999,
      currency: 'IDR',
      trend: 'down',
      trendPercentage: 3,
      trendLabel: 'Turun dibanding bulan lalu',
    },
    {
      id: 'net-worth',
      title: 'Net Worth',
      value: 2_999_999_997,
      currency: 'IDR',
      trend: 'up',
      trendPercentage: 5,
      trendLabel: 'Naik dibanding bulan lalu',
    },
  ],
  monthlyRevenue: [
    { month: 'Jan', bcaIdr: 48, bcaUsd: 32, cash: 24 },
    { month: 'Feb', bcaIdr: 62, bcaUsd: 72, cash: 41 },
    { month: 'Mar', bcaIdr: 51, bcaUsd: 89, cash: 70 },
    { month: 'Apr', bcaIdr: 45, bcaUsd: 64, cash: 52 },
    { month: 'May', bcaIdr: 39, bcaUsd: 48, cash: 45 },
    { month: 'Jun', bcaIdr: 31, bcaUsd: 34, cash: 37 },
    { month: 'Jul', bcaIdr: 42, bcaUsd: 72, cash: 28 },
    { month: 'Aug', bcaIdr: 65, bcaUsd: 90, cash: 33 },
    { month: 'Sep', bcaIdr: 52, bcaUsd: 60, cash: 48 },
    { month: 'Oct', bcaIdr: 55, bcaUsd: 45, cash: 51 },
    { month: 'Nov', bcaIdr: 61, bcaUsd: 52, cash: 49 },
    { month: 'Dec', bcaIdr: 58, bcaUsd: 57, cash: 53 },
  ],
  incomeBreakdown: [
    {
      category: 'BCA IDR',
      value: 12_000_000_000,
      percentage: 45,
      color: '#ECB45B',
    },
    {
      category: 'BCA USD',
      value: 99_999_999,
      percentage: 35,
      color: '#B0160D',
    },
    {
      category: 'Cash',
      value: 234_932_000,
      percentage: 20,
      color: '#1C3A58',
    },
  ],
  accounts: [
    {
      id: 'bca-usd',
      name: 'BCA (USD)',
      subtitle: 'Bank Account - USD',
      currency: 'USD',
      type: 'bank',
      openingBalance: 0,
      debit: 9_999_999_999,
      credit: 9_999_999_999,
      closingBalance: 999_999_999,
      accentColor: '#6BA6FF',
    },
    {
      id: 'bca-idr',
      name: 'BCA (IDR)',
      subtitle: 'Bank Account - IDR',
      currency: 'IDR',
      type: 'bank',
      openingBalance: 0,
      debit: 9_999_999_999,
      credit: 9_999_999_999,
      closingBalance: 999_999_999,
      accentColor: '#F38B82',
    },
    {
      id: 'cash',
      name: 'CASH (IDR)',
      subtitle: 'Cash on hand (IDR)',
      currency: 'IDR',
      type: 'cash',
      openingBalance: 0,
      debit: 9_999_999_999,
      credit: 9_999_999_999,
      closingBalance: 999_999_999,
      accentColor: '#82D9A5',
    },
  ],
  financeSeries: [
    { month: 'jan', income: { bcaUsd: 2.5, bcaIdr: 3.2, cash: 1.8 }, expense: { bcaUsd: 1.8, bcaIdr: 2.4, cash: 1.2 } },
    { month: 'feb', income: { bcaUsd: 5.4, bcaIdr: 6.9, cash: 4.0 }, expense: { bcaUsd: 2.4, bcaIdr: 3.5, cash: 2.1 } },
    { month: 'mar', income: { bcaUsd: 9.8, bcaIdr: 7.2, cash: 5.2 }, expense: { bcaUsd: 3.2, bcaIdr: 3.8, cash: 2.3 } },
    { month: 'apr', income: { bcaUsd: 7.3, bcaIdr: 5.8, cash: 4.1 }, expense: { bcaUsd: 4.1, bcaIdr: 5.4, cash: 3.0 } },
    { month: 'may', income: { bcaUsd: 4.8, bcaIdr: 4.2, cash: 3.2 }, expense: { bcaUsd: 3.6, bcaIdr: 3.8, cash: 2.5 } },
    { month: 'jun', income: { bcaUsd: 3.6, bcaIdr: 3.9, cash: 3.5 }, expense: { bcaUsd: 5.1, bcaIdr: 4.8, cash: 3.1 } },
    { month: 'jul', income: { bcaUsd: 6.2, bcaIdr: 4.9, cash: 2.1 }, expense: { bcaUsd: 6.7, bcaIdr: 5.9, cash: 2.9 } },
    { month: 'aug', income: { bcaUsd: 8.9, bcaIdr: 6.1, cash: 3.6 }, expense: { bcaUsd: 4.6, bcaIdr: 3.4, cash: 2.2 } },
    { month: 'sep', income: { bcaUsd: 4.4, bcaIdr: 3.7, cash: 4.2 }, expense: { bcaUsd: 3.5, bcaIdr: 2.8, cash: 2.4 } },
    { month: 'oct', income: { bcaUsd: 4.9, bcaIdr: 3.5, cash: 4.9 }, expense: { bcaUsd: 4.2, bcaIdr: 3.1, cash: 3.5 } },
    { month: 'nov', income: { bcaUsd: 5.3, bcaIdr: 3.8, cash: 5.1 }, expense: { bcaUsd: 3.8, bcaIdr: 2.6, cash: 2.7 } },
    { month: 'dec', income: { bcaUsd: 5.7, bcaIdr: 3.9, cash: 5.3 }, expense: { bcaUsd: 3.9, bcaIdr: 2.9, cash: 2.9 } },
  ],
  customers: {
    totalCustomers: 23,
    totalRevenue: { idr: 364_993_000, usd: 99_222.98 },
    averageRevenue: 23,
    topCustomers: [
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
      { name: 'PT Mass Berg Ground', revenue: 234_000_000 },
    ],
  },
  products: {
    totalProducts: 65,
    totalSold: 1_293,
    topProducts: [
      { name: 'Honda Vario XX', quantity: 23 },
      { name: 'Kawasaki XX', quantity: 21 },
      { name: 'PT Mass Berg Ground', quantity: 1 },
      { name: 'PT Mass Berg Ground', quantity: 19 },
      { name: 'PT Mass Berg Ground', quantity: 11 },
    ],
  },
  cashflow: {
    incomes: [
      { account: 'BCA USD', amount: 99_999_999, currency: 'USD' },
      { account: 'BCA IDR', amount: 12_000_000_000, currency: 'IDR' },
      { account: 'Cash', amount: 234_932_000, currency: 'IDR' },
    ],
    outcomes: [
      { account: 'BCA USD', amount: 99_999_999, currency: 'USD' },
      { account: 'BCA IDR', amount: 12_000_000_000, currency: 'IDR' },
      { account: 'Cash', amount: 234_932_000, currency: 'IDR' },
    ],
  },
  transactions: [
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Vario XX',
      customer: 'PT Indah Sekali',
      account: 'BCA IDR',
      total: 24_874_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Vario XX',
      customer: 'PT Indah Sekali',
      account: 'BCA IDR',
      total: 24_874_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Headlamp',
      customer: 'PT Indah Sekali',
      account: 'CASH',
      total: 345_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Headlamp',
      customer: 'PT Indah Sekali',
      account: 'CASH',
      total: 345_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Headlamp',
      customer: 'PT Indah Sekali',
      account: 'CASH',
      total: 345_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Headlamp',
      customer: 'PT Indah Sekali',
      account: 'CASH',
      total: 345_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Headlamp',
      customer: 'PT Indah Sekali',
      account: 'CASH',
      total: 345_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Kawasaki XX',
      customer: 'PT Indah Saja',
      account: 'BCA USD',
      total: 3_341_000,
      currency: 'USD',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Kawasaki XX',
      customer: 'PT Indah Saja',
      account: 'BCA USD',
      total: 3_341_000,
      currency: 'USD',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
    {
      note: 'TRX-011',
      date: '2026-12-31T00:00:00.000Z',
      sale: 'Vario XX',
      customer: 'PT Indah Saja',
      account: 'BCA IDR',
      total: 24_874_000,
      currency: 'IDR',
      description: 'Penjualan vario xx sejumlah xx oleh PT XX',
      type: 'income',
    },
  ],
  lastUpdated: new Date().toISOString(),
};
