stages:
  # - build
  # - test
  - deploy

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"

# # =========================
# # GLOBAL BEFORE SCRIPT
# # =========================
# default:
#   before_script:
#     - 'echo "🚧 Runner: $(hostname)"'
#     - 'echo "👤 User: $(whoami)"'
#     - 'docker --version || true'

# # =========================
# # BASE TEMPLATE
# # =========================
# .default-dev: &default-dev
#   tags:
#     - stagging
#     - deraly
#     - hq
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "development"'

.default-prod: &default-prod
  tags:
    - cloud
    - wajira
    - production
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'


# # =========================
# # DEVELOPMENT PIPELINE
# # =========================
# build-dev:
#   <<: *default-dev
#   stage: build
#   script:
#     - echo "Build development (optional)"

# test-dev:
#   <<: *default-dev
#   stage: test
#   script:
#     - echo "Testing development (optional)"

# deploy-dev:
#   <<: *default-dev
#   stage: deploy
#   environment:
#     name: staging
#   script:
#     - echo "Deploy to staging"


# # =========================
# # PRODUCTION PIPELINE
# # =========================
# build-prod:
#   <<: *default-prod
#   stage: build
#   script:
#     - echo "Build production (optional)"

# test-prod:
#   <<: *default-prod
#   stage: test
#   script:
#     - echo "Testing production (optional)"

deploy-prod:
  <<: *default-prod
  stage: deploy
  environment:
    name: production
  script:
    - echo "BISMILLAHIROHMANIROHIM"
    - echo "Suro diro joyo diningrat, lebur dening pangastuti."
    - echo "Brokohan kakang kawah Adi Ari-adi, Mugi-mugi Gusti pinaring kalancaran, tebih saking error 500, cinaketaken kaliyan status ijo mbranang puniko."

    - |
      sudo -u wajira-team bash << 'EOF'
      set -e

      echo "REKSO BUMI MINONGKO PIPELINE!"
      
      echo "Bismillah, cekelanku!"
      
      cd /home/wajira-team/production/finance-dash && git pull origin master && docker container stop wajira-finance-dashboard && docker container rm wajira-finance-dashboard && docker rmi wajira-finance-dashboard:latest &&       docker compose -f docker-compose.prod.yaml build --no-cache && docker compose -f docker-compose.prod.yaml up -d && docker compose restart
      
      sleep 5

      EOF
  before_script:
    - echo "Niat ingsun ngresiki bug, masang kode ingkang pener minulya manuungsa..."
  after_script:
    - echo "Gusti Pinaringan, pipeline ijo mbranang, sukses rahayu, rahayu wilujeng!"