version: "3.9"

services:
  wajira-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wajira-panel-ui
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=https://wajirabackend.hawk-dev.com
      - NEXT_PUBLIC_AUTH_DOMAIN=wajirabackend.hawk-dev.com