version: "3.8"

services:
  wajira-finance-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wajira-finance-frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - NEXT_PUBLIC_AUTH_DOMAIN=http://202.74.75.47:3000
    networks:
      - wajira-local-net

networks:
  wajira-local-net:
    external: true
